### ISSUE TITLE
Caffe to CNNdroid

### ISSUE THREAD

**Issue by lMagal** [hirorogithub/CNNdroid_age_demo#1]
Caffe转换成CNNdroid，  配置文件需要自己手动根据prototxt文件转成CNNdroid的配置文件吗

**Comment by hirorogithub** [comment]
是的,他们换了一点描述方式,可以参考readme里我的blog里写的信息进行转换

**Comment by lMagal** [comment]
请问一下caffe里面对应的
 type: "Scale"
  type: "BatchNorm"
的类型转换成CNNdroid的对应是什么？
CNNdroid是不是不全部支持caffe里面的所有类型
我刚接触，对深度学习这块是个小白， 拿了个caffe的模型来测试， 配置文件转换的不懂

**Comment by hirorogithub** [comment]
其实我也不是搞深度学习的,我也只是跟着官方给的样例,根据对应的网络修改而已

**Comment by lMagal** [comment]
好的， 谢谢
